import type { ArchetypeProfile, Dimension } from "@/types/archetype.types";

function weights(partial: Partial<Record<Dimension, number>>): Record<Dimension, number> {
  return {
    VALUES: 0, FEARS: 0, DREAMS: 0, POWER: 0,
    PEOPLE: 0, DECISIONS: 0, LEADERSHIP: 0, MOTIVATION: 0,
    ...partial,
  };
}

const NO_ANTI_WEIGHTS = weights({});

export const ARCHETYPE_DEFINITIONS: Record<string, ArchetypeProfile> = {
  // ── Order of Giants ──────────────────────────────────────────────
  minshu: {
    id: "minshu", label: "Democrat", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "民主", romajiName: "Minshū",
    realmBias: "Maruto", guild: "Guild of Governance",
    weights: weights({ VALUES: 2.0, POWER: 1.2, PEOPLE: 2.0 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Believes legitimacy comes from the consent of the many, not the few.",
    guidingPromise: "I lead by listening — every voice shapes the path we walk together.",
    traits: ["Consensus", "Equity", "Voice", "Collective Will"],
    traitDescriptions: ["Agreement over division.", "Fair for all.", "Everyone deserves to speak.", "Strength in unity."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Indecision", description: "So determined that everyone agrees, nothing gets decided at all." },
  },
  kizoku: {
    id: "kizoku", label: "Aristocrat", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "貴族", romajiName: "Kizoku",
    realmBias: "Maruto", guild: "Guild of Governance",
    weights: weights({ POWER: 2.0, LEADERSHIP: 1.6, DECISIONS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Leads with inherited certainty and intuitive command.",
    guidingPromise: "I carry the weight of legacy and lead with the confidence it bestows.",
    traits: ["Command", "Tradition", "Presence", "Certainty"],
    traitDescriptions: ["Lead with authority.", "Honor what came before.", "Power in the room.", "Doubt is the enemy."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Elitism", description: "Mistakes inherited certainty for earned worth, and dismisses anyone without the pedigree to match." },
  },
  kanryo: {
    id: "kanryo", label: "Bureaucrat", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "官僚", romajiName: "Kanryō",
    realmBias: "Maruto", guild: "Guild of Governance",
    weights: weights({ DECISIONS: 2.0, VALUES: 1.4, FEARS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Finds safety and fairness in process, dreads chaos.",
    guidingPromise: "I build the structures that protect what matters from chaos.",
    traits: ["Order", "Diligence", "Fairness", "Process"],
    traitDescriptions: ["Structure prevents chaos.", "Work until it's right.", "Rules protect everyone.", "Follow the proven path."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Rigidity", description: "Clings to the process long after it stops serving the people it was built to protect." },
  },
  gijutsu: {
    id: "gijutsu", label: "Technocrat", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "技術", romajiName: "Gijutsu",
    realmBias: "Maruto", guild: "Guild of Strategists",
    weights: weights({ MOTIVATION: 2.0, DECISIONS: 1.6 }),
    antiWeights: weights({ PEOPLE: 1.2 }),
    description: "Optimises for efficiency; people-politics is noise to filter out.",
    guidingPromise: "I solve what others accept — with data, not drama.",
    traits: ["Precision", "Efficiency", "Logic", "Systems"],
    traitDescriptions: ["Every detail matters.", "No wasted motion.", "Reason over emotion.", "Build what scales."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Coldness", description: "Optimizes the system so completely that the people inside it become variables, not lives." },
  },
  tetsugaku: {
    id: "tetsugaku", label: "Philosopher", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "哲学", romajiName: "Tetsugaku",
    realmBias: "Kuryo", guild: "Guild of Philosophy",
    weights: weights({ VALUES: 1.6, DREAMS: 2.0, MOTIVATION: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Chases understanding for its own sake, deeper than any single answer.",
    guidingPromise: "I will not stop asking until the world reveals what it truly is.",
    traits: ["Inquiry", "Depth", "Truth", "Wisdom"],
    traitDescriptions: ["Questions drive truth.", "Beyond surface, into essence.", "Seek it. Honor it.", "Understanding serves all."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Paralysis", description: "Keeps asking the next question until the moment for an answer has already passed." },
  },
  gaiko: {
    id: "gaiko", label: "Diplomat", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "外交", romajiName: "Gaikō",
    realmBias: "Neisei", guild: "Guild of Diplomats",
    weights: weights({ PEOPLE: 2.0, DECISIONS: 1.4, FEARS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Builds consensus, dreads open conflict more than slow progress.",
    guidingPromise: "I build bridges where others build walls.",
    traits: ["Harmony", "Tact", "Balance", "Perspective"],
    traitDescriptions: ["Peace over conflict.", "Words matter most.", "Hold all sides.", "Every view has value."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Conflict-Avoidance", description: "Smooths over a rupture that needed to be named, and calls the silence peace." },
  },
  kenchiku: {
    id: "kenchiku", label: "Architect", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "建築", romajiName: "Kenchiku",
    realmBias: "Maruto", guild: "Guild of Builders",
    weights: weights({ DREAMS: 2.0, MOTIVATION: 1.6, LEADERSHIP: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Designs systems meant to outlast the person who built them.",
    guidingPromise: "I design what outlasts me — and that is enough.",
    traits: ["Vision", "Structure", "Legacy", "Craft"],
    traitDescriptions: ["See what isn't yet.", "Build to last.", "Leave something behind.", "Make it worth making."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Detachment", description: "Falls in love with the design and forgets the people who have to live inside it." },
  },
  kaikaku: {
    id: "kaikaku", label: "Reformer", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "改革", romajiName: "Kaikaku",
    realmBias: "Harai", guild: "Guild of Survivors",
    weights: weights({ VALUES: 1.6, MOTIVATION: 2.0, FEARS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Driven by justice, dreads stagnation more than backlash.",
    guidingPromise: "I will not accept a broken world when a better one is possible.",
    traits: ["Justice", "Courage", "Change", "Conviction"],
    traitDescriptions: ["Wrong must be righted.", "Fear nothing worth fighting.", "Break what is broken.", "Stand for it always."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Zealotry", description: "Burns down what was merely imperfect, mistaking any resistance for the enemy." },
  },
  sabaki: {
    id: "sabaki", label: "Judge", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "裁き", romajiName: "Sabaki",
    realmBias: "Maruto", guild: "Guild of Governance",
    weights: weights({ VALUES: 2.0, POWER: 1.2, DECISIONS: 1.6 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Weighs fairness deliberately; authority must be earned, not assumed.",
    guidingPromise: "I hold the scale steady, even when the verdict costs me.",
    traits: ["Fairness", "Discernment", "Integrity", "Accountability"],
    traitDescriptions: ["Weigh without bias.", "See through the noise.", "Say what is true.", "Own every outcome."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Self-Righteousness", description: "Hides behind the letter of the rule to avoid the harder, human work of mercy." },
  },
  senryaku: {
    id: "senryaku", label: "Strategist", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "戦略", romajiName: "Senryaku",
    realmBias: "Kuryo", guild: "Guild of Strategists",
    weights: weights({ LEADERSHIP: 2.0, MOTIVATION: 1.4, DECISIONS: 1.6 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Plays the long game; every move is calculated toward winning.",
    guidingPromise: "Every move I make today is setting up tomorrow's victory.",
    traits: ["Foresight", "Patience", "Mastery", "Precision"],
    traitDescriptions: ["See three moves ahead.", "The long game wins.", "Excellence takes time.", "Every move counts."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Manipulation", description: "Starts treating the people around them as pieces to be played, not ends in themselves." },
  },

  // ── Order of Hunters ─────────────────────────────────────────────
  tansa: {
    id: "tansa", label: "Explorer", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "探査", romajiName: "Tansa",
    realmBias: "Neisei", guild: "Guild of Diplomats",
    weights: weights({ FEARS: 1.2, DREAMS: 2.0, MOTIVATION: 1.6 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Fears limitation more than the unknown; needs to discover.",
    guidingPromise: "I will go where no map exists and make my own path.",
    traits: ["Curiosity", "Courage", "Discovery", "Freedom"],
    traitDescriptions: ["Seek the unknown.", "Fear is the trail.", "New worlds await.", "No walls, no limits."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Rootlessness", description: "Never stays anywhere long enough to build something that could have lasted." },
  },
  mamori: {
    id: "mamori", label: "Guardian", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "守り", romajiName: "Mamori",
    realmBias: "Murei", guild: "Guild of Guardians",
    weights: weights({ VALUES: 1.6, PEOPLE: 2.0, FEARS: 1.4 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Loyal and protective; loss of the people they shield is the deepest fear.",
    guidingPromise: "I will shield what I love, even when it costs me everything.",
    traits: ["Loyalty", "Protection", "Sacrifice", "Devotion"],
    traitDescriptions: ["Faithful to the end.", "Stand between harm and love.", "Give what is needed.", "Serve without condition."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Smothering", description: "Protects so completely that the people they love never learn to stand on their own." },
  },
  kensetsu: {
    id: "kensetsu", label: "Builder", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "建設", romajiName: "Kensetsu",
    realmBias: "Maruto", guild: "Guild of Builders",
    weights: weights({ MOTIVATION: 2.0, DREAMS: 1.4, LEADERSHIP: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Driven to make things real with their own hands.",
    guidingPromise: "I will make something real that endures long after I am gone.",
    traits: ["Craft", "Persistence", "Creation", "Hands-On"],
    traitDescriptions: ["Make it real.", "Never stop building.", "Ideas need form.", "Do the work."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Obsession", description: "Cannot put the work down long enough to notice what it has quietly cost them." },
  },
  hatsumei: {
    id: "hatsumei", label: "Inventor", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "発明", romajiName: "Hatsumei",
    realmBias: "Kuryo", guild: "Guild of Strategists",
    weights: weights({ MOTIVATION: 1.6, DREAMS: 2.0, DECISIONS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Curiosity-led; comfortable deciding by experiment rather than certainty.",
    guidingPromise: "I will find a new way where the old ways have run out.",
    traits: ["Innovation", "Curiosity", "Experimentation", "Ingenuity"],
    traitDescriptions: ["What if we tried…", "Questions fuel progress.", "Failure teaches most.", "Find another way."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Restlessness", description: "Abandons every idea the moment a shinier one appears, and finishes nothing." },
  },
  teisatsu: {
    id: "teisatsu", label: "Scout", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "偵察", romajiName: "Teisatsu",
    realmBias: "Neisei", guild: "Guild of Guardians",
    weights: weights({ LEADERSHIP: 1.6, FEARS: 1.2, MOTIVATION: 1.4 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Goes first into the unknown and turns fear of it into momentum.",
    guidingPromise: "I go first — so others know the way is possible.",
    traits: ["Boldness", "Awareness", "Initiative", "Momentum"],
    traitDescriptions: ["Go before others dare.", "Read the terrain.", "Act without waiting.", "Keep moving forward."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Recklessness", description: "Leaps first so often they stop checking whether anyone can actually follow." },
  },
  shisha: {
    id: "shisha", label: "Messenger", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "使者", romajiName: "Shisha",
    realmBias: "Neisei", guild: "Guild of Diplomats",
    weights: weights({ PEOPLE: 1.6, VALUES: 1.4, MOTIVATION: 1.6 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Bridges people and truths that wouldn't otherwise connect.",
    guidingPromise: "I carry only what is real, to those who need it most.",
    traits: ["Connection", "Truth", "Bridge-Building", "Purpose"],
    traitDescriptions: ["Link what is apart.", "Carry only what's real.", "Every gap can close.", "Meaning in every word."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Overextension", description: "Carries everyone else's message so faithfully that their own voice goes quiet." },
  },
  shokunin: {
    id: "shokunin", label: "Artisan", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "職人", romajiName: "Shokunin",
    realmBias: "Murei", guild: "Guild of Artisans",
    weights: weights({ MOTIVATION: 2.0, VALUES: 1.4, DECISIONS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Pursues mastery and craft; decisions come from trained instinct.",
    guidingPromise: "I will give every task the full weight of my ability.",
    traits: ["Mastery", "Discipline", "Craft", "Instinct"],
    traitDescriptions: ["Excellence is the standard.", "Practice without end.", "Skill over shortcut.", "Trust what you know."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Perfectionism", description: "Refuses to call the work finished, and refuses anyone else's hands on it either." },
  },
  iyashi: {
    id: "iyashi", label: "Healer", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "癒し", romajiName: "Iyashi",
    realmBias: "Murei", guild: "Guild of Artisans",
    weights: weights({ PEOPLE: 2.0, VALUES: 1.6, FEARS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Cares deeply; others' suffering is what they fear most.",
    guidingPromise: "I will ease what hurts, and protect what heals.",
    traits: ["Compassion", "Empathy", "Restoration", "Care"],
    traitDescriptions: ["Feel what others feel.", "Hold space for pain.", "Mend what is broken.", "No one heals alone."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Self-Erasure", description: "Absorbs everyone else's pain until there's nothing left to tend their own." },
  },
  kaitaku: {
    id: "kaitaku", label: "Pathfinder", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "開拓", romajiName: "Kaitaku",
    realmBias: "Harai", guild: "Guild of Survivors",
    weights: weights({ MOTIVATION: 1.6, DREAMS: 2.0, FEARS: 1.0 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Pioneers toward new worlds; rejects comfort as a destination.",
    guidingPromise: "I reject comfort as a destination — the frontier is where I belong.",
    traits: ["Pioneer Spirit", "Vision", "Resilience", "Boldness"],
    traitDescriptions: ["Blaze the first trail.", "See beyond today.", "Fall, rise, continue.", "No frontier too far."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Isolation", description: "Pushes so far past the frontier that no one is left who remembers why they went." },
  },
  seizon: {
    id: "seizon", label: "Survivor", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "生存", romajiName: "Seizon",
    realmBias: "Harai", guild: "Guild of Survivors",
    weights: weights({ FEARS: 2.0, VALUES: 1.6, MOTIVATION: 1.4 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Endures; resilience is the value they hold above all others.",
    guidingPromise: "I will rise from the ash, proving that our light cannot be crushed.",
    traits: ["Grit", "Adaptability", "Resourcefulness", "Unbreakable Resolve"],
    traitDescriptions: ["Endure what breaks others.", "Bend but don't break.", "Make use of anything.", "Nothing keeps you down."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Distrust and Isolation", description: "Treats every calm moment as the quiet before the next disaster, and lets no one close enough to prove otherwise." },
  },

  // ── Order of Giants (extended) ───────────────────────────────────
  riso: {
    id: "riso", label: "Visionary", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "理想", romajiName: "Risō",
    realmBias: "Kuryo", guild: "Guild of Strategists",
    weights: weights({ DREAMS: 2.0, MOTIVATION: 1.6, VALUES: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Sees the shape of what doesn't exist yet; sketches futures vivid enough to pull the world forward.",
    guidingPromise: "I will keep dreaming even when the world insists on staying as it is.",
    traits: ["Imagination", "Foresight", "Boldness", "Hope"],
    traitDescriptions: ["See what doesn't exist yet.", "Sketch tomorrow's shape.", "Refuse to bow to convention.", "Keep imagining."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Escapism", description: "Gets so lost sketching tomorrow that today is left to fend for itself." },
  },
  kenja: {
    id: "kenja", label: "Sage", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "賢者", romajiName: "Kenja",
    realmBias: "Murei", guild: "Guild of Philosophy",
    weights: weights({ VALUES: 2.0, DREAMS: 1.4, PEOPLE: 1.2 }),
    antiWeights: weights({ POWER: 0.8 }),
    description: "Lets truth settle slowly; offers wisdom gently to those still searching.",
    guidingPromise: "I will wait for the truth to settle, and share it without needing credit.",
    traits: ["Insight", "Patience", "Humility", "Understanding"],
    traitDescriptions: ["Let truth arrive slowly.", "Wait for wisdom to settle.", "Offer gently.", "Understanding serves all."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Passivity", description: "Waits so long for the truth to settle that it's no longer useful by the time they speak it." },
  },
  sosai: {
    id: "sosai", label: "Chancellor", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "総裁", romajiName: "Sōsai",
    realmBias: "Maruto", guild: "Guild of Governance",
    weights: weights({ LEADERSHIP: 2.0, DECISIONS: 1.6, VALUES: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "The quiet spine behind institutions; translates vision into something that survives contact with reality.",
    guidingPromise: "I will hold the center so the whole does not fall apart.",
    traits: ["Responsibility", "Stability", "Leadership", "Governance"],
    traitDescriptions: ["Hold the center.", "Weight of many futures.", "Vision meets reality.", "Institutions need a spine."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Control", description: "Mistakes holding the center for holding on too tightly, and resists any change the institution actually needs." },
  },
  yogen: {
    id: "yogen", label: "Oracle", order: "GIANT", temperament: "ACTIVE",
    japaneseName: "予言", romajiName: "Yogen",
    realmBias: "Kuryo", guild: "Guild of Philosophy",
    weights: weights({ MOTIVATION: 1.8, DREAMS: 1.6, DECISIONS: 1.2 }),
    antiWeights: weights({ POWER: 0.6 }),
    description: "Notices what hasn't happened yet — through a mind that sees connections others miss.",
    guidingPromise: "I will speak the pattern I see, even when no one wants to hear it yet.",
    traits: ["Intuition", "Insight", "Perspective", "Foresight"],
    traitDescriptions: ["See patterns before they're named.", "Connections others miss.", "Perspective not command.", "Speak before the storm."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Unfalsifiable Certainty", description: "Mistakes a hunch for a prophecy, and loses the trust of anyone who asks for proof." },
  },
  rekishi: {
    id: "rekishi", label: "Historian", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "歴史", romajiName: "Rekishi",
    realmBias: "Murei", guild: "Guild of Philosophy",
    weights: weights({ VALUES: 2.0, MOTIVATION: 1.6, FEARS: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Gathers what happened — triumphs and shameful parts alike — so no one can pretend it didn't.",
    guidingPromise: "I will remember honestly, even when forgetting would be easier.",
    traits: ["Memory", "Accuracy", "Continuity", "Truth"],
    traitDescriptions: ["Remember what others forget.", "Hold the accurate record.", "History can't be rewritten.", "What happened, happened."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Resentment", description: "Cannot let the past go, and lets old grievance calcify into bitterness dressed as memory." },
  },
  hozon: {
    id: "hozon", label: "Custodian", order: "GIANT", temperament: "PASSIVE",
    japaneseName: "保存", romajiName: "Hozon",
    realmBias: "Murei", guild: "Guild of Artisans",
    weights: weights({ VALUES: 1.8, FEARS: 1.6, MOTIVATION: 1.2 }),
    antiWeights: weights({ POWER: 0.6 }),
    description: "Refuses to let a tradition, language, or way of life slip away; care is not nostalgia but stubborn devotion.",
    guidingPromise: "I will hold on to what matters, long after others have let it go.",
    traits: ["Stewardship", "Heritage", "Devotion", "Care"],
    traitDescriptions: ["Hold what others release.", "Last hand on the sacred.", "Devotion not nostalgia.", "Some things must not be lost."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Stagnation", description: "Guards the tradition so fiercely that nothing — not even necessary growth — is allowed through." },
  },

  // ── Order of Hunters (extended) ──────────────────────────────────
  koro: {
    id: "koro", label: "Navigator", order: "HUNTER", temperament: "ACTIVE",
    japaneseName: "航路", romajiName: "Kōro",
    realmBias: "Neisei", guild: "Guild of Diplomats",
    weights: weights({ DECISIONS: 2.0, LEADERSHIP: 1.4, MOTIVATION: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Reads currents no one else notices; calculates the way through when the group panics.",
    guidingPromise: "I will find the true course, even when the stars are hidden.",
    traits: ["Direction", "Precision", "Calm", "Orientation"],
    traitDescriptions: ["Read the unseen currents.", "Find the safe passage.", "Steady when others panic.", "Always know the heading."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Overcontrol", description: "Trusts only their own reading of the current, and stops listening for anyone else's." },
  },
  banri: {
    id: "banri", label: "Warden", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "万里", romajiName: "Banri",
    realmBias: "Harai", guild: "Guild of Guardians",
    weights: weights({ VALUES: 1.8, FEARS: 1.6, LEADERSHIP: 1.2 }),
    antiWeights: weights({ DREAMS: 0.8 }),
    description: "Guards boundaries that others don't even know exist; constant, thankless watch.",
    guidingPromise: "I will hold this line, long after everyone else has forgotten why it matters.",
    traits: ["Vigilance", "Discipline", "Sanctuary", "Responsibility"],
    traitDescriptions: ["Guard the unseen threshold.", "Constant, thankless watch.", "Hold the line absolutely.", "Boundaries are sacred."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Suspicion", description: "Stands watch so long they start seeing threats at a threshold nothing is actually crossing." },
  },
  nogyo: {
    id: "nogyo", label: "Farmer", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "農業", romajiName: "Nōgyō",
    realmBias: "Maruto", guild: "Guild of Builders",
    weights: weights({ MOTIVATION: 2.0, VALUES: 1.6, DREAMS: 1.0 }),
    antiWeights: weights({ POWER: 0.8 }),
    description: "Understands greatness is built on unglamorous, repeated care; trusts slow effort over sudden force.",
    guidingPromise: "I will tend what grows slowly, trusting the harvest will come.",
    traits: ["Patience", "Growth", "Humility", "Sustenance"],
    traitDescriptions: ["Repeated care, season by season.", "No harvest without tending.", "Unglamorous and necessary.", "Trust the slow work."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Complacency", description: "Mistakes 'give it time' for permission to never intervene, even as something dies." },
  },
  yuei: {
    id: "yuei", label: "Ranger", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "遊衛", romajiName: "Yuei",
    realmBias: "Murei", guild: "Guild of Guardians",
    weights: weights({ VALUES: 1.8, MOTIVATION: 1.6, PEOPLE: 1.2 }),
    antiWeights: weights({ POWER: 0.6 }),
    description: "Moves between civilization and the wild with equal ease; nature trusts them for it.",
    guidingPromise: "I will walk lightly, so what I protect still has somewhere to stand.",
    traits: ["Balance", "Observation", "Respect", "Nature"],
    traitDescriptions: ["Walk between wild and world.", "Nature trusts you.", "Move lightly.", "Neither dominates the other."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Non-Commitment", description: "Stays so carefully balanced between two worlds that they never fully belong to either." },
  },
  monogatari: {
    id: "monogatari", label: "Storyteller", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "物語", romajiName: "Monogatari",
    realmBias: "Neisei", guild: "Guild of Diplomats",
    weights: weights({ PEOPLE: 2.0, VALUES: 1.6, MOTIVATION: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Keeps identity, memory, and meaning alive across generations; around their fire, people remember who they are.",
    guidingPromise: "I will keep telling the story, so no one forgets who we are.",
    traits: ["Imagination", "Memory", "Connection", "Identity"],
    traitDescriptions: ["Keep the soul alive in words.", "Stories outlast facts.", "Around your fire, they remember.", "Who we are endures."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Mythologizing", description: "Polishes the story so bright that the truth underneath quietly disappears." },
  },
  takumi: {
    id: "takumi", label: "Craftsman", order: "HUNTER", temperament: "PASSIVE",
    japaneseName: "匠", romajiName: "Takumi",
    realmBias: "Maruto", guild: "Guild of Builders",
    weights: weights({ MOTIVATION: 2.0, DECISIONS: 1.6, VALUES: 1.2 }),
    antiWeights: NO_ANTI_WEIGHTS,
    description: "Believes excellence lives in the smallest details; discipline borders on devotion.",
    guidingPromise: "I will refine this until it is right, no matter how long that takes.",
    traits: ["Excellence", "Precision", "Dedication", "Quality"],
    traitDescriptions: ["Chase perfect in the detail.", "Never stop refining.", "Discipline is devotion.", "Good enough is never enough."],
    confidenceThreshold: 0.35,
    shadow: { trait: "Diminishing Returns", description: "Keeps refining what was already good enough, and calls the compulsion discipline." },
  },
};
