import type { SurveyQuestion } from "./survey-questions";

// Tamil translation of survey-question-bank.ts — same id/dimension/type
// per question, same order per dimension, so the seeded selection in
// survey-selection.engine.ts picks identical questions across languages.
export const QUESTION_BANK: SurveyQuestion[] = [
  // ── VALUES ────────────────────────────────────────────────────────
  { id: "val-01", dimension: "VALUES", type: "likert", text: "எனக்குத் தெரிஞ்ச ஒரு விஷயம் தப்புன்னு நான் நினைச்சாலும், அத விட்டுடறதுக்கு நான் ரொம்ப ready-ஆ இருக்கேன்." },
  { id: "val-02", dimension: "VALUES", type: "yesno", text: "நீங்க follow பண்ற personal rules ஏதாவது இருக்கா?" },
  { id: "val-03", dimension: "VALUES", type: "likert", text: "எல்லாரும் என் கூட disagree பண்ணாலும், எனக்குத் தெரிஞ்ச fair-ஆன விஷயத்த விட்டுக்கொடுக்கறது ரொம்ப கஷ்டம்." },
  { id: "val-04", dimension: "VALUES", type: "yesno", text: "உங்களுக்கு ஏதாவது பிடிச்சிருந்தாலும், அது தப்பா இருக்கும்னு நெனச்சி அத விட்டுட்டீங்களா?" },
  { id: "val-05", dimension: "VALUES", type: "likert", text: "மத்தவங்களுக்குப் தெரியலன்னாலும், நான் சொன்ன வாக்குறுதிய நிறைவேத்தறது எனக்கு முக்கியம்." },
  { id: "val-06", dimension: "VALUES", type: "yesno", text: "உங்கள் நற்பெயருக்குக் களங்கம் ஏற்படுத்தினாலும், அநியாயமாக நடத்தப்பட்ட ஒருவருக்கு நீங்கள் ஆதரவாக நிற்கிறீர்களா?" },
  { id: "val-07", dimension: "VALUES", type: "likert", text: "சூழ்நிலை மாறினாலும், நான் என் செயல்களை எப்பவுமே ஒரே standard வெச்சுதான் பார்ப்பேன்." },
  { id: "val-08", dimension: "VALUES", type: "yesno", text: "எவ்வளவு கிடைச்சாலும், நீங்க ஒருபோதும் பண்ணவே மாட்டேன்னு ஒரு விஷயம் இருக்கா?" },
  { id: "val-09", dimension: "VALUES", type: "likert", text: "உண்மை கொஞ்சம் கஷ்டமா இருந்தாலும், அமைதியா இருக்கறத விட, honest-ஆ இருக்கறதுதான் எனக்கு முக்கியம்." },
  { id: "val-10", dimension: "VALUES", type: "yesno", text: "தன் வசதிக்கு ஏத்த மாதிரி values-ஐ மாத்திக்கிற ஆளுங்களை respect பண்றது உங்களுக்கு கஷ்டமா இருக்கா?" },
  { id: "val-11", dimension: "VALUES", type: "likert", text: "நான் பாத்த நிலைமையை விட, விஷயங்களை இன்னும் நல்லா வெச்சுட்டு போகணும்னு எனக்குள்ள ஒரு அமைதியான கடமை உணர்வு இருக்கு." },
  { id: "val-12", dimension: "VALUES", type: "yesno", text: "ஒரு வாக்குறுதி நிறைவேத்தறது கஷ்டமா ஆன பிறகும், அத நீங்க நீண்ட நாள் காப்பாத்தி இருக்கீங்களா?" },
  { id: "val-13", dimension: "VALUES", type: "likert", text: "efficient-ஆ இருக்கறத விட, fair-ஆ இருக்கறதுதான் எனக்கு முக்கியம்." },
  { id: "val-14", dimension: "VALUES", type: "yesno", text: "நீங்க கவனிக்கிற ஒருத்தருக்கு, சொல்லாம இருக்கறது அவங்களை காப்பாத்தும்னாலும், கஷ்டமான உண்மைய சொல்வீங்களா?" },

  // ── FEARS ─────────────────────────────────────────────────────────
  { id: "fear-01", dimension: "FEARS", type: "likert", text: "என் own standard-க்கு ஏத்த மாதிரி இருக்க முடியலைன்னு நான் அடிக்கடி கவலைப்படுவேன்." },
  { id: "fear-02", dimension: "FEARS", type: "yesno", text: "ஒரு வேலையில fail ஆறத விட, ஒருத்தர் trust-ஐ இழக்கிறது உங்களுக்கு இன்னும் மோசமா தோணுமா?" },
  { id: "fear-03", dimension: "FEARS", type: "likert", text: "வேலைய செய்யறதை விட, என் வேலை மறந்துடும்னு நினைக்கிறதுதான் எனக்கு இன்னும் கஷ்டமா இருக்கு." },
  { id: "fear-04", dimension: "FEARS", type: "yesno", text: "தப்பு பண்றத பத்தி பயப்படுறத விட, முக்கியத்துவம் இல்லாம போயிடுவோமோன்னு நீங்க இன்னும் பயப்படுறீங்களா?" },
  { id: "fear-05", dimension: "FEARS", type: "likert", text: "நான் நேசிக்கிற ஒரு விஷயத்த ஒரே நேரத்துல இழக்கிறத விட, அது மெதுவா நொறுங்கிப் போறத பாக்கிறதுதான் எனக்கு இன்னும் பயமா இருக்கு." },
  { id: "fear-06", dimension: "FEARS", type: "yesno", text: "நெருங்கின ஆளுங்க உங்களை misunderstand பண்ணிடுவாங்களோன்னு நினைச்சு, ராத்திரி தூக்கம் வராம இருக்குமா?" },
  { id: "fear-07", dimension: "FEARS", type: "likert", text: "conflict-ஐ விட, chaos-உம் ஒழுங்கீனமும்தான் என்னை இன்னும் கஷ்டப்படுத்தும்." },
  { id: "fear-08", dimension: "FEARS", type: "yesno", text: "கஷ்டமான வாழ்க்கைய விட, சாதாரண வாழ்க்கைதான் உங்களுக்கு இன்னும் பயமா இருக்கா?" },
  { id: "fear-09", dimension: "FEARS", type: "likert", text: "என்னைப் பத்தி கவலைப்படுறத விட, நான் காப்பாத்தற ஆளுங்களைப் பத்திதான் நான் இன்னும் கவலைப்படுவேன்." },
  { id: "fear-10", dimension: "FEARS", type: "yesno", text: "தப்பான வழியில போறத விட, ஒரே இடத்துல நின்னுடறதுதான் உங்களுக்கு இன்னும் பயமா இருக்கா?" },
  { id: "fear-11", dimension: "FEARS", type: "likert", text: "வெளியில இருந்து வர எந்த ஆபத்தை விட, நான் வளராம நின்னுடலாம்னு நினைக்கிறதுதான் எனக்கு இன்னும் பயமா இருக்கு." },
  { id: "fear-12", dimension: "FEARS", type: "yesno", text: "விட்டுட்டுப் போறது ஒருத்தர மேல கை விட்டுடற மாதிரி தோணுனதால, நீங்க வேணும்ன்னதுக்கும் மேல ஒரு சண்டையில நின்னிருக்கீங்களா?" },
  { id: "fear-13", dimension: "FEARS", type: "likert", text: "அதிகமா யாருக்காவது தேவைப்பட்டு வருஷக்கணக்கா இருக்கிறத விட, யாருக்கும் தேவையில்லாம போற நாள் வருமோன்னுதான் எனக்கு இன்னும் பயமா இருக்கு." },
  { id: "fear-14", dimension: "FEARS", type: "yesno", text: "முக்கியமான தகவல் என்றென்றைக்குமா இழந்துடுமோன்னு நினைக்கிறது உங்களை disturb பண்ணுமா?" },

  // ── DREAMS ────────────────────────────────────────────────────────
  { id: "drm-01", dimension: "DREAMS", type: "likert", text: "இந்த உலகத்துல நான் என்ன மாதிரி ஒரு அடையாளத்த விட்டுட்டுப் போகணும்னு நான் அடிக்கடி யோசிப்பேன்." },
  { id: "drm-02", dimension: "DREAMS", type: "yesno", text: "நீங்க இப்போ ஒரு குறிப்பிட்ட future-க்காக வேலை பண்றீங்களா?" },
  { id: "drm-03", dimension: "DREAMS", type: "likert", text: "ஒரு நல்ல உலகத்த நான் தெளிவா கற்பனை பண்ண முடியும், அது என்னை ஈர்க்கும்." },
  { id: "drm-04", dimension: "DREAMS", type: "yesno", text: "நீங்க போன பிறகும் நிலைக்கிற ஒரு விஷயத்த உருவாக்கணும்னு dream பண்றீங்களா?" },
  { id: "drm-05", dimension: "DREAMS", type: "likert", text: "பழக்கமான வசதிய விட, புது இடங்கள்-real-ஆ இருந்தாலும் ideas-ல இருந்தாலும்-என்னை இன்னும் அதிகமா கூப்பிடும்." },
  { id: "drm-06", dimension: "DREAMS", type: "yesno", text: "விட்டுட முடியாத ஒரு vision-க்காக உங்க வாழ்க்கையோட direction-ஐ மாத்தி இருக்கீங்களா?" },
  { id: "drm-07", dimension: "DREAMS", type: "likert", text: "நான் என்ன சொந்தம் பண்ணுவேன்-ங்கறத விட, என்னால என்ன சாத்தியப்படுத்த முடியும்-ங்கறதுதான் என் goals." },
  { id: "drm-08", dimension: "DREAMS", type: "yesno", text: "நேரம் தீருறதுக்குள்ள செய்யணும்னு நினைக்கிற விஷயங்களோட ஒரு private list நீங்க வெச்சிருக்கீங்களா?" },
  { id: "drm-09", dimension: "DREAMS", type: "likert", text: "என் best future-ஐ நான் கற்பனை பண்ணும்போது, மத்தவங்களும் அதுல நல்லா இருப்பாங்க." },
  { id: "drm-10", dimension: "DREAMS", type: "yesno", text: "சரியான நேரத்துக்காக காத்திருந்து, வருஷக்கணக்கா நீங்க சுமந்துக்கிட்டு வர்ற ஒரு idea இருக்கா?" },
  { id: "drm-11", dimension: "DREAMS", type: "likert", text: "நாளைக்கு ஏதாவது amazing-ஆ கிடைக்கும்னு chance இருந்தா, இன்னைக்கு இருக்கிற certainty-ஐ நான் விட்டுடுவேன்." },
  { id: "drm-12", dimension: "DREAMS", type: "yesno", text: "உங்க real life's work இன்னும் முழுசா ஆரம்பிக்கல-ன்னு உங்களுக்கு தோணுதா?" },
  { id: "drm-13", dimension: "DREAMS", type: "likert", text: "நான் இப்போ நிக்கிற இடத்த விட, முன்னாடி என்ன இருக்குன்னதுதான் எனக்கு இன்னும் interest-ஆ இருக்கு." },
  { id: "drm-14", dimension: "DREAMS", type: "yesno", text: "நீங்க உண்மையா எதை விரும்புறீங்களோ, அதுக்காக முழுசா புது இடத்துல மறுபடியும் ஆரம்பிப்பீங்களா?" },

  // ── POWER ─────────────────────────────────────────────────────────
  { id: "pow-01", dimension: "POWER", type: "likert", text: "நான் responsibility எடுத்துக்கிட்டோ, மத்தவங்களுக்கு direction காட்டும்போதோதான் எனக்கு அதிகபட்ச energy கிடைக்கும்." },
  { id: "pow-02", dimension: "POWER", type: "yesno", text: "confusion-ஆன situation வரும்போது, மக்கள் பதிலுக்காக உங்க கிட்ட வருவாங்களா?" },
  { id: "pow-03", dimension: "POWER", type: "likert", text: "authority வெச்சிருக்கறது எனக்கு பரவாயில்லை. accountable-ஆ இருக்கணும்னா நான் தயங்க மாட்டேன்." },
  { id: "pow-04", dimension: "POWER", type: "yesno", text: "வேற ஒருத்தர் power-ஐ நல்லா use பண்ணுவாங்கன்னு trust பண்றத விட, நீங்களே அதை வெச்சுக்கறது நல்லதுன்னு நினைக்கறீங்களா?" },
  { id: "pow-05", dimension: "POWER", type: "likert", text: "நீங்க பண்றதுல நல்லா இருந்தா தான் influence கிடைக்கணும்னு நான் நம்புறேன், அத நானே எனக்குள்ள follow பண்றேன்." },
  { id: "pow-06", dimension: "POWER", type: "yesno", text: "யாரும் தொடவே தயங்குற ஒரு fail ஆயிட்ட situation-ஐ நீங்க எடுத்துக்கிட்டு நடத்தி இருக்கீங்களா?" },
  { id: "pow-07", dimension: "POWER", type: "likert", text: "decision-க்கு முகமா இருக்கறத விட, அதுக்கு பின்னாடி அமைதியா வேலை பண்றதுதான் எனக்கு comfortable." },
  { id: "pow-08", dimension: "POWER", type: "yesno", text: "respect இல்லாத ஒரு leader-ஐ follow பண்றது-அது உங்களுக்கு cost ஆனாலும்கூட-கஷ்டமா இருக்குமா?" },
  { id: "pow-09", dimension: "POWER", type: "likert", text: "ஒருத்தர் மேல எனக்கு power இருக்கும்போது, அதோட perks-ஐ விட அதோட weight-தான் எனக்கு அதிகமா தோணும்." },
  { id: "pow-10", dimension: "POWER", type: "yesno", text: "அது நல்லா இருக்கணும்னா, நீங்க கட்டி எழுப்பின ஒரு விஷயத்தோட control-ஐ நீங்க விட்டுடுவீங்களா?" },
  { id: "pow-11", dimension: "POWER", type: "likert", text: "எனக்கு rules-ஹ்னா tools மாதிரி. follow பண்றதுக்கும் தகுதி இருக்கு, மாத்றதுக்கும் தகுதி இருக்கு." },
  { id: "pow-12", dimension: "POWER", type: "yesno", text: "ஒரு charming leader-ஐ விட, rules and systems-ஐ நீங்க இன்னும் அதிகமா trust பண்றீங்களா?" },
  { id: "pow-13", dimension: "POWER", type: "likert", text: "நூறு பேரை பொது இடத்துல lead பண்றத விட, பத்து பேருக்கு அமைதியா power கிடைக்க உதவறதுதான் எனக்கு பிடிக்கும்." },
  { id: "pow-14", dimension: "POWER", type: "yesno", text: "நீங்க ready-ஆ இருக்கறதுக்கு முன்னாடியே responsibility உங்களை தேடி வந்திருக்கா?" },

  // ── PEOPLE ────────────────────────────────────────────────────────
  { id: "ppl-01", dimension: "PEOPLE", type: "likert", text: "என்ன சுத்தி இருக்கிற ஆளுங்களோட mood-உம் wellbeing-உம், நான் என்ன feel பண்றேன்-ங்கறதையும் நான் எடுக்கிற decision-ஐயும் ரொம்ப affect பண்ணும்." },
  { id: "ppl-02", dimension: "PEOPLE", type: "yesno", text: "ஒருத்தர் சொல்றதுக்கு முன்னாடியே, அவங்க எப்படி feel பண்றாங்கன்னு உங்களால usually உணர முடியுமா?" },
  { id: "ppl-03", dimension: "PEOPLE", type: "likert", text: "ரூம்ல யாரு விட்டு வைக்கப்பட்டு இருக்காங்கன்னு நான் தானா தேடிப் பாப்பேன்." },
  { id: "ppl-04", dimension: "PEOPLE", type: "yesno", text: "தெரியாத ஆளுங்க கூட, அவங்க யாருக்குமே சொல்லாத விஷயங்களை உங்ககிட்ட அடிக்கடி சொல்லிடுவாங்களா?" },
  { id: "ppl-05", dimension: "PEOPLE", type: "likert", text: "நான் கவனிக்கிற ஆளுங்க சண்டை போட்டா, அது என் feelings மட்டுமில்ல, என் body-ஐயும் affect பண்ணும்." },
  { id: "ppl-06", dimension: "PEOPLE", type: "yesno", text: "ஒருத்தருக்கு நீங்க தேவைப்பட்டதால, நீங்க நினைச்சதுக்கும் மேல ஒரு இடத்துல நின்னிருக்கீங்களா?" },
  { id: "ppl-07", dimension: "PEOPLE", type: "likert", text: "ஆளுங்க தங்க வாழ்க்கை பத்தி சொல்ற சின்ன சின்ன details-ஐ நான் வருஷக்கணக்கா நினைவு வெச்சுக்குவேன்." },
  { id: "ppl-08", dimension: "PEOPLE", type: "yesno", text: "ஒரு group பிரிஞ்சுப் போகும்போது, அதோட பாகங்களை இணைக்கிற bridge-ஆ நீங்க மாறுவீங்களா?" },
  { id: "ppl-09", dimension: "PEOPLE", type: "likert", text: "ஒரு disagreement-ஐ சீக்கிரமா வெல்றத விட, மெதுவா முழுசா தீர்க்கிறதுதான் எனக்கு பிடிக்கும்." },
  { id: "ppl-10", dimension: "PEOPLE", type: "yesno", text: "நிறைய பேருக்கு பிடிச்சிருக்கிறது விட, சில பேருக்கு ஆழமா தெரிஞ்சிருக்கிறதுதான் உங்களுக்கு முக்கியமா?" },
  { id: "ppl-11", dimension: "PEOPLE", type: "likert", text: "நான் கொடுத்த ஒரு விஷயத்தால ஒருத்தர் வளர்றத பாக்கிறது, என் சொந்த வெற்றிகளை விட எனக்கு நல்லா தோணும்." },
  { id: "ppl-12", dimension: "PEOPLE", type: "yesno", text: "மத்தவங்களோட சுமையை உங்களோட சுமை மாதிரியே நீங்க சுமக்கிற பழக்கம் இருக்கா?" },
  { id: "ppl-13", dimension: "PEOPLE", type: "likert", text: "மத்தவங்க என்னை slow பண்ணினாலும், தனியா வேலை பண்றத விட, மத்தவங்க கூட வேலை பண்றதுதான் எனக்கு நல்லா வரும்." },
  { id: "ppl-14", dimension: "PEOPLE", type: "yesno", text: "அவங்க ஏன் அப்படி பண்ணாங்கன்னு நீங்க புரிஞ்சுக்கிட்டதால, ஒருத்தரை நீங்க மன்னிச்சிருக்கீங்களா?" },

  // ── DECISIONS ─────────────────────────────────────────────────────
  { id: "dec-01", dimension: "DECISIONS", type: "likert", text: "முக்கியமான ஒரு விஷயத்துக்கு commit பண்றதுக்கு முன்னாடி, என்னால முடிஞ்ச அளவுக்கு எல்லாத்தையும் தெரிஞ்சுக்க நான் முதல்ல முயற்சி பண்ணுவேன்." },
  { id: "dec-02", dimension: "DECISIONS", type: "yesno", text: "clear-ஆ ஒரு plan இருந்தா, ஒரு விஷயத்த ஆரம்பிக்கும்போது நீங்க இன்னும் confident-ஆ feel பண்றீங்களா?" },
  { id: "dec-03", dimension: "DECISIONS", type: "likert", text: "ஏன் அந்த decision எடுத்தேன்-ன்னு exact-ஆ explain பண்ண முடிஞ்சா, அந்த decision-ஐ நான் இன்னும் அதிகமா trust பண்ணுவேன்." },
  { id: "dec-04", dimension: "DECISIONS", type: "yesno", text: "facts-உம் instinct-உம் disagree ஆகும்போது, நீங்க usually facts-ஓடதான் நிக்கறீங்களா?" },
  { id: "dec-05", dimension: "DECISIONS", type: "likert", text: "முழுசா யோசிக்காம ஒரு choice எடுக்கறத விட, அதை delay பண்றதுதான் எனக்கு பிடிக்கும்." },
  { id: "dec-06", dimension: "DECISIONS", type: "yesno", text: "வேற மாதிரி என்ன பண்ணி இருக்கலாம்னு புரிஞ்சுக்க, முன்னாடி எடுத்த decisions-ஐ நீங்க replay பண்ணிப் பாப்பீங்களா?" },
  { id: "dec-07", dimension: "DECISIONS", type: "likert", text: "ஒரு crisis வரும்போது, மத்தவங்க speed ஆகும்போது, நான் இன்னும் calm-ஆவும் organized-ஆவும் ஆயிடுவேன்." },
  { id: "dec-08", dimension: "DECISIONS", type: "yesno", text: "ஒரே ஒரு moment-ல ஒரு major life decision எடுத்து, அதை ஒருபோதும் regret பண்ணாம இருந்திருக்கீங்களா?" },
  { id: "dec-09", dimension: "DECISIONS", type: "likert", text: "இன்னைக்கு அது எப்படி feel ஆகுதுன்னதை விட, பத்து வருஷம் கழிச்சு அந்த choice எப்படி இருக்கும்-ங்கறதைதான் நான் இன்னும் அதிகமா யோசிப்பேன்." },
  { id: "dec-10", dimension: "DECISIONS", type: "yesno", text: "முழுசா commit பண்றதுக்கு முன்னாடி, சின்னதா test பண்றதுதான் உங்களுக்கு பிடிக்குமா?" },
  { id: "dec-11", dimension: "DECISIONS", type: "likert", text: "ஒருதடவை decide பண்ணிட்டா, நான் திரும்பி பாக்க மாட்டேன். second-guess பண்ண எனக்கு time இல்ல." },
  { id: "dec-12", dimension: "DECISIONS", type: "yesno", text: "வழி clear-ஆ இல்லாதப்போ, நீங்க எப்படியோ முன்னாடி போய், கத்துக்கிட்டே adjust பண்ணிக்குவீங்களா?" },
  { id: "dec-13", dimension: "DECISIONS", type: "likert", text: "problem-ஓட முதல்ல தனியா time செலவழிச்ச பிறகுதான் நான் என் best decisions எடுப்பேன்." },
  { id: "dec-14", dimension: "DECISIONS", type: "yesno", text: "திடீர்னு வர்ற inspiration-ஐ விட, காலப்போக்குல நீங்க improve பண்ணின methods-ஐதான் இன்னும் அதிகமா trust பண்றீங்களா?" },

  // ── LEADERSHIP ────────────────────────────────────────────────────
  { id: "led-01", dimension: "LEADERSHIP", type: "likert", text: "orders கொடுக்கிறத விட, example-ஆ இருந்துதான் lead பண்ணணும்னு நான் நம்புறேன்." },
  { id: "led-02", dimension: "LEADERSHIP", type: "yesno", text: "group situations-ல, கேக்காமலேயே நீங்க அடிக்கடி step up பண்றீங்களா?" },
  { id: "led-03", dimension: "LEADERSHIP", type: "likert", text: "யாரும் திறக்க தயங்குற ஒரு கதவை முதல்ல திறந்து போக நான் தயாரா இருப்பேன்." },
  { id: "led-04", dimension: "LEADERSHIP", type: "yesno", text: "நீங்க வழி காட்டினதால, ஆளுங்க கஷ்டமான ஒரு விஷயத்துக்குள்ள உங்களை follow பண்ணி வந்திருக்காங்களா?" },
  { id: "led-05", dimension: "LEADERSHIP", type: "likert", text: "ஒரு நல்ல leader blame-ஐ தானே எடுத்துக்கிட்டு, credit-ஐ மத்தவங்களுக்கு கொடுப்பாரு. நானும் அப்படித்தான் இருக்க முயற்சி பண்ணுவேன்." },
  { id: "led-06", dimension: "LEADERSHIP", type: "yesno", text: "நீங்களே ஒரு famous leader ஆறத விட, பத்து அமைதியான leaders-ஐ train பண்றதுதான் உங்களுக்கு பிடிக்குமா?" },
  { id: "led-07", dimension: "LEADERSHIP", type: "likert", text: "ஒரு group வழி தப்பினா, அத மறுபடியும் கண்டுபிடிக்கிறது என் வேலைன்னு எனக்கு தோணும்." },
  { id: "led-08", dimension: "LEADERSHIP", type: "yesno", text: "யாரை lead பண்றீங்க-ங்கறதுக்கு ஏத்த மாதிரி, நீங்க வேற வேற மாதிரி lead பண்றீங்களா?" },
  { id: "led-09", dimension: "LEADERSHIP", type: "likert", text: "day-to-day details manage பண்றத விட, long-term direction set பண்றதுதான் எனக்கு பிடிக்கும்." },
  { id: "led-10", dimension: "LEADERSHIP", type: "yesno", text: "நீங்க lead பண்ணணும்னு விரும்பினாலும், வேற ஒருத்தர் இன்னும் suit ஆவாங்கன்னதால, நீங்க step back பண்ணி இருக்கீங்களா?" },
  { id: "led-11", dimension: "LEADERSHIP", type: "likert", text: "எல்லாமே uncertain-ஆ தோணுற நேரங்கள்ல தான், ஆளுங்க என்னை இன்னும் அதிகமா trust பண்றாங்க மாதிரி தோணும்." },
  { id: "led-12", dimension: "LEADERSHIP", type: "yesno", text: "உங்களை இல்லாமலேயே succeed ஆக, உங்களை சுத்தி இருக்கிற ஆளுங்களை நீங்க prepare பண்றீங்களா?" },
  { id: "led-13", dimension: "LEADERSHIP", type: "likert", text: "நானே என்னை இன்னும் உயர்ந்த standards-ல வெச்சுக்கறதால, நான் lead பண்றவங்களையும் high standards-ல வெச்சிருப்பேன்." },
  { id: "led-14", dimension: "LEADERSHIP", type: "yesno", text: "உங்க watch-ல ஏதாவது தப்பா போனா, அத பொது இடத்துல own பண்றதுதான் உங்க முதல் instinct-ஆ?" },

  // ── MOTIVATION ────────────────────────────────────────────────────
  { id: "mot-01", dimension: "MOTIVATION", type: "likert", text: "கடைசில கிடைக்கிற reward-ஐ விட, ஒரு விஷயத்துல நான் improve ஆறதுதான் என்னை இன்னும் அதிகமா drive பண்ணும்." },
  { id: "mot-02", dimension: "MOTIVATION", type: "yesno", text: "கிட்டத்தட்ட தினமும் நீங்களே யோசிச்சுக்கிட்டு இருக்கிற ஒரு goal இருக்கா?" },
  { id: "mot-03", dimension: "MOTIVATION", type: "likert", text: "என் கைகளால அல்லது மனசால ஏதாவது பண்ணும்போதோ fix பண்ணும்போதோதான், நேரம் போனதே தெரியாம நான் இருப்பேன்." },
  { id: "mot-04", dimension: "MOTIVATION", type: "yesno", text: "எல்லாருக்கும் already முடிஞ்சதுன்னு தோணுற வேலைய, நீங்க திரும்பி போய் improve பண்றீங்களா?" },
  { id: "mot-05", dimension: "MOTIVATION", type: "likert", text: "பதில் கிடைக்காத ஒரு question, நான் அத solve பண்ணற வரைக்கும் நாள்கணக்கா என் மனசுல இருக்கும்." },
  { id: "mot-06", dimension: "MOTIVATION", type: "yesno", text: "ஒரு skill தெரியாதது உங்களை bother பண்ணினதால மட்டுமே, நீங்களே அத கத்துக்கிட்டு இருக்கீங்களா?" },
  { id: "mot-07", dimension: "MOTIVATION", type: "likert", text: "வேலை கஷ்டமா, slow-ஆ, ஏறத்தாழ யாரும் பாக்காம இருக்கும்போதுதான் நான் என் best-ஆ இருப்பேன்." },
  { id: "mot-08", dimension: "MOTIVATION", type: "yesno", text: "அத solve பண்றது பாக்கப்படுறத விட, problem-ஐ solve பண்றதுதான் உங்களுக்கு முக்கியமா?" },
  { id: "mot-09", dimension: "MOTIVATION", type: "likert", text: "ஒவ்வொரு தடவையும் கொஞ்சம் நல்லா ஆகும்னா, ஒரு task-ஐ repeat பண்றது எனக்கு bore ஆகாது." },
  { id: "mot-10", dimension: "MOTIVATION", type: "yesno", text: "real progress இல்லாம நிறைய நேரம் ஓடிடுச்சுன்னா, நீங்க restless-ஆ feel பண்றீங்களா?" },
  { id: "mot-11", dimension: "MOTIVATION", type: "likert", text: "மத்தவங்க கை விட்ட problems-கிட்டதான் நான் இன்னும் ஈர்க்கப்படுவேன்." },
  { id: "mot-12", dimension: "MOTIVATION", type: "yesno", text: "உங்களுக்கு paid ஆகாம, praise கிடைக்காமலேயே இருந்தாலும், உங்க most important work-ஐ நீங்க தொடர்ந்து பண்ணிக்கிட்டே இருப்பீங்களா?" },
  { id: "mot-13", dimension: "MOTIVATION", type: "likert", text: "discipline-ஐ விட, curiosity தான் என் வாழ்க்கையில என்னை இன்னும் தூரம் கூட்டிட்டு போயிருக்கு." },
  { id: "mot-14", dimension: "MOTIVATION", type: "yesno", text: "ஆரம்ப excitement போன நெடுநாள் கழிச்சும், நீங்க ஆரம்பிச்சத முடிக்கிறீங்களா?" },
];
