# Sample persona — Toyuho Kagemori (the Survivor), extracted from the
# Dossier 1.0 sample so 2.0 preserves every original feature. In
# production this structure is generated from the participant's record.

PERSONA = {
    "real_name": "Rajeev",
    "birth_name": "Toyuho",
    "legacy_name": "Toyuho Kagemori",
    "gv_id": "GV-TOY23",
    "order": "Order of Hunters",
    "order_short": "HUNTERS",
    "motto": "I will rise from the ash, proving that our light cannot be crushed.",
    "archetype": "Survivor",
    "archetype_jp": "Seizon",
    "archetype_kanji": "生存",
    "archetype_desc": "Endures; resilience is the value they hold above all others.",
    "confidence": 82,
    "secondary": "Builder",
    "secondary_jp": "Kensetsu",
    "secondary_pct": 51,
    "growth_note": "Builder (Kensetsu) — the wheel-neighbour your scores already lean toward. Growth in the Giantverse is a drift, not a leap.",
    "shadow_name": "Distrust and Isolation",
    "shadow_desc": "Treats every calm moment as the quiet before the next disaster, and lets no one close enough to prove otherwise.",
    "realm_name": "The Broken Heart",
    "realm_jp": "Harai",
    "realm_desc": "Where survival becomes renewal. Not a fixed place, but what Maruto becomes when civilization falls out of balance. Harai is temporary by nature — when balance returns, it transforms back into Maruto, a cycle called The Great Turning.",
    "guild": "Guild of Survivors",
    "guild_tagline": "Those who endure, adapt, and begin again.",
    "symbol": "The Relit Hearth",
    "symbol_meaning": "Endurance is not the absence of ash — it is the second fire.",
    "traits": [
        ("GRIT", "Endure what breaks others."),
        ("ADAPTABILITY", "Bend but don't break."),
        ("RESOURCEFULNESS", "Make use of anything."),
        ("UNBREAKABLE RESOLVE", "Nothing keeps you down."),
    ],
    "facets": [
        ("Leadership", 25), ("Creativity", 40), ("Discipline", 42),
        ("Communication", 39), ("Decision Making", 25),
    ],
    "field_notes": [
        ("STRESS BEHAVIOUR", "Under pressure, plays not-to-lose — options narrow to the safest. Recovery comes through pricing the cost of the safe option out loud."),
        ("LEARNING STYLE", "Learns by safety — masters material fastest in low-stakes reps before any public test."),
        ("DECISION MAKING", "The Survivor decides through grit first and unbreakable resolve last — reversing that order is the most common self-reported regret of this archetype."),
    ],
    "wheel": {
        "position_note": "Position 24 of 32 — the Survivor (Seizon).",
        "neighbours": "Builder (Kensetsu) · Scout (Teisatsu) — the directions of natural drift as your answers evolve.",
        "compatible": "Reformer · Pathfinder — your fellow members of the Guild of Survivors.",
        "opposite": "Philosopher (Tetsugaku) — not an enemy: the other answer to your shared question.",
        "question": "Should we understand first, or endure first?",
        "growth": "Toward the Builder — the neighbour your scores already lean into.",
        "order32": ["Survivor", "Scout", "Storyteller", "Navigator", "Ranger", "Artisan", "Craftsman", "Democrat",
                    "Judge", "Bureaucrat", "Chancellor", "Strategist", "Technocrat", "Oracle", "Philosopher", "Sage",
                    "Historian", "Visionary", "Architect", "Diplomat", "Messenger", "Inventor", "Warden", "Farmer",
                    "Aristocrat", "Reformer", "Pathfinder", "Guardian", "Healer", "Builder", "Explorer", "Custodian"],
        "you_idx": 0, "neighbour_idxs": [29, 1], "guild_idxs": [25, 26], "opposite_idx": 14,
    },
    "lore_realm": [
        ("ANCIENT HISTORY", "Harai has no founding date because Harai is not a place — it is what Maruto becomes when balance fails. Every continent's histories record its visits: the drought years, the siege years, the years the ledgers burned. And every history records the same ending: The Great Turning, when Harai becomes Maruto again."),
        ("CULTURE", "Harai culture is triage made noble. Rank means little; usefulness means everything. Its people share tools before names and count wealth in what still works. Humour survives here in its driest, toughest form."),
        ("TRADITIONS", "The First Repair: when a community begins recovery, the first thing rebuilt is chosen by the youngest present. Whatever they pick — a well, a doorway, a toy — is restored with full ceremony, to prove that rebuilding has rules of the heart, not only of need."),
    ],
    "lore_craft": [
        ("ARCHITECTURE", "Salvage-built and honest about it: braced ruins, patched vaults, new walls seamed visibly into old. Harai builders leave the damage legible — a structure should remember what it survived."),
        ("WEAPONS", "Whatever is at hand, maintained obsessively. The Harai blade is notched, oiled, and utterly reliable. Doctrine is simple: waste nothing, especially not people."),
        ("SYMBOLS", "The visible seam; the relit hearth; the broken circle redrawn — not closed, but continuing."),
    ],
    "lore_legend": [
        "They speak of the Ash Registrar, who walks ruined districts recording not what was lost but what was saved, and whose ledger — read aloud at the Great Turning — is said to be the longest poem in the world.",
        "Every child of The Broken Heart grows up on this story. Whether Toyuho Kagemori believes it, resents it, or is quietly trying to live up to it — that choice is character design, and it is yours to make.",
    ],
    "lore_guild": [
        ("ORIGIN", "Chartered in the ashes of the Third Harai, when the relief crews who had improvised the recovery refused to disband, arguing — correctly — that they would be needed again."),
        ("THE OATH", "“I endure, I adapt, and I leave a path behind me.”"),
        ("THE HALL", "The Seam Hall, rebuilt in every generation from the salvage of the most recent disaster, its walls a visible chronology of everything the continents have withstood."),
    ],
    "lore_guild2": [
        ("THE RITE OF ENTRY", "Initiates are given a ruined thing — tool, map, plan, reputation — and one season to return it to service. Perfection is not required; function is."),
        ("REPUTATION", "The Guild everyone hopes never to need and everyone eventually thanks. Survivors are famously impossible to insult and impossible to stop."),
    ],
    "lore_story": {
        "title": "The Inventory of What Was Saved",
        "sub": "The story every Survivor is measured against.",
        "body": "After the flood, while others counted losses, a Seizon read aloud the list of what remained — three boats, one forge, all the children. The reading became the Ash Registrar's tradition, and the Survivors' answer to despair: begin from the assets.",
        "cultural": "Seizon greet each other with 'Still here' — statement, question, and toast in two words.",
        "closing": "One day, the record-keepers will tell a story like this about Toyuho Kagemori. The pages that follow — the Hero Journey — are its first draft.",
    },
    "cast": [
        ("THE HERO", "The Builder You Are Becoming", "Builder · Kensetsu · Order of Hunters", "THE RAISED BEAM",
         "Your scores already lean toward the Builder — the wheel's natural next step from Survivor.",
         "They act where you deliberate, and deliberate where you act; travelling together, each of you covers the other's blind quarter.",
         "Craft is not a departure from Grit — it is where Grit goes next."),
        ("THE HEROINE", "The Craftsman of the Crossing Path", "Craftsman · Takumi · Order of Hunters", "THE FINAL PASS",
         "A quarter-turn across the wheel: close enough to understand you, far enough to surprise you.",
         "Where your instinct says \"Endure what breaks others\", theirs says \"Chase perfect in the detail\" — and the story lives in the negotiation.",
         "Precision — the strength you respect most because it costs you the most to practise."),
        ("THE MENTOR", "The Elder Reformer of the Guild of Survivors", "Reformer · Kaikaku · Order of Giants", "THE BROKEN CIRCLE REDRAWN",
         "Your own Guild, the other Order — proof your Calling can be answered a different way.",
         "They will not correct your path; they will show you the map of theirs and let the difference teach.",
         "\"I will not accept a broken world when a better one is possible.\" — a promise you were never asked to make, kept by someone who shares your hall."),
        ("THE RIVAL", "The Philosopher Across the Wheel", "Philosopher · Tetsugaku · Order of Giants", "THE HALF-CLOSED EYE",
         "You answer the same question differently: Should we understand first, or endure first?",
         "Every plan you make, they counter — not from malice, but from a whole life of the other answer. Beating them requires understanding them.",
         "The day you can argue their answer at full strength is the day your own answer becomes earned instead of inherited."),
        ("THE ALLY", "The Scout at Your Shoulder", "Scout · Teisatsu · Order of Hunters", "THE FIRST FOOTPRINT",
         "Your other wheel-neighbour — near enough to trust on sight, different enough to be useful.",
         "No speeches, no ceremony: they simply appear where you need a second pair of hands, already working.",
         "Initiative — offered so casually you'll almost miss that it's a discipline."),
        ("THE MONSTER", "The Beast of Distrust and Isolation", "A figure beyond the wheel", "◆",
         "Every archetype's shadow, loosed into the world, takes a shape. Yours is distrust and isolation — made vast, made hungry.",
         "Treats every calm moment as the quiet before the next disaster, and lets no one close enough to prove otherwise. As a creature, it does this to whole villages at a time.",
         "It cannot be slain by your strength — your strength is what feeds it. It is starved by the thing you find hardest."),
        ("THE VILLAIN", "The Fallen Philosopher", "Philosopher · Tetsugaku · Order of Giants", "THE HALF-CLOSED EYE",
         "Not your opposite — your opposite's shadow, paralysis, with an army and a grievance.",
         "Keeps asking the next question until the moment for an answer has already passed. They believe, sincerely, that this is the only answer left to the question you both carry.",
         "They are what your Rival becomes without you — which means your Rival is what they could have been with you."),
        ("THE SHADOW SELF", "The Survivor, Unchecked", "Survivor · Seizon · Order of Hunters", "THE RELIT HEARTH",
         "Distrust and Isolation: your own signature strength, grit, taken to the extreme where it stops serving anyone.",
         "Treats every calm moment as the quiet before the next disaster, and lets no one close enough to prove otherwise.",
         "The shadow is not defeated once. It is out-practised daily — usually by borrowing one habit from your Opposite."),
    ],
    "team": [
        ("KENSETSU", "The Builder", "Momentum — the Builder converts your grit into motion."),
        ("KAIKAKU", "The Reformer", "Perspective — the Reformer has already paid for the lessons you're about to buy."),
        ("KAITAKU", "The Pathfinder", "Depth — a fellow member of the Guild of Survivors, fluent in your Calling's craft."),
    ],
    "journey": [
        ("Why You Were Chosen", "Toyuho Kagemori was not chosen for being flawless. The Order of Hunters marked them because, of everyone in The Broken Heart, they alone answered the old question the way a Survivor must — endures; resilience is the value they hold above all others. The Giant Hunt does not summon the strongest. It summons the necessary."),
        ("The Quest", "To carry the relit hearth across all five realms and prove that \"I will rise from the ash, proving that our light cannot be crushed.\" is not a motto but a method — sealing their name, Toyuho become Toyuho Kagemori, into the record of the Hunt."),
        ("The Greatest Fear", "Not death, and not defeat — distrust and isolation. Treats every calm moment as the quiet before the next disaster, and lets no one close enough to prove otherwise. Toyuho Kagemori has seen this happen to greater Survivors, and lies awake knowing the difference between them was never talent."),
        ("The Hidden Strength", "Beneath the Survivor runs a quieter current of the Builder: craft, surfacing exactly when the primary path fails. Enemies who prepare for a Survivor are never prepared for that."),
        ("The Greatest Trial", "The Hunt will force the question the wheel has always asked of them — and their answer will pull them toward the Builder's path or harden them against it. The trial is not the Giant. The trial is choosing, at full cost, in front of everyone, what a Survivor is for."),
        ("The Transformation", "They enter the Hunt a Survivor and leave something the wheel has no single name for: a Survivor who has learned the Builder's craft without surrendering their own grit. The shadow of distrust and isolation does not vanish — it is finally, daily, out-practised."),
        ("The Final Destiny", "A place among the Hunters' honoured names — the Survivor whose path becomes a route others can walk, whose grit outlives the Hunt that demanded it."),
    ],
    "blueprint": {
        "shape": "TRIANGLE",
        "shape_word": "triangle",
        "shape_note": "Lead with triangles in costume blocking, props and hair masses; use the opposing shape family only for the shadow-self and villain variants.",
        "shape_why": "Grit and Adaptability are triangle-family traits in classical design theory.",
        "build": "Agile proportions: 6.5–7 heads with longer limb ratio, weight on the balls of the feet. Built to be drawn mid-stride.",
        "silhouette": "Directional and dynamic — a silhouette with a point: angled shoulders or hips, asymmetric layers, gear that sweeps toward the character's intent.",
        "palette": [
            ("Ash Char", "#33302E", "Primary — garments, base tone"),
            ("Seam Grey", "#B9B3AA", "Secondary — patches, visible repairs"),
            ("Ember Rust", "#9A4A2E", "Support — worn edges, heat marks"),
            ("Hunter Signal", "#FF6467", "Accent — Order insignia, eyes of the design"),
        ],
        "palette_note": "The Broken Heart materials with the Hunter signal accent. Keep the accent under ten percent of the design — it should be findable, not loud.",
        "print_note": "Print note — these values are screen hexes; when working in markers or paint, match by eye against the printed chips above rather than the numbers.",
        "head": [
            ("FACE & EYES", "Angular cheekbones, keen tapered eyes, sharp hair spikes or a swept cut that carries the diagonal into the face."),
            ("HAIR", "Swept, directional masses with 2–3 large spike groups — avoid many small spikes, which fragment the read."),
            ("PERSONALITY EXPRESSION", "Default expression carries grit; the 'tell' — the micro-expression under stress — should hint at distrust and isolation without stating it."),
        ],
        "head_note": "A character's shadow belongs in the acting long before it enters the plot.",
        "wardrobe": [
            ("COSTUME", "Base layers in The Broken Heart materials (see palette), cut in triangle-family blocks; one field layer carrying the Guild of Survivors insignia at chest or shoulder."),
            ("ACCESSORIES", "A worn, personal token referencing \"The Relit Hearth\" — small enough for close-ups, distinctive enough for merchandise."),
            ("WEAPON / TOOL", "Whatever is at hand, maintained obsessively."),
            ("TEXTURES", "Visible repairs: seams, patches, re-stitched panels. Damage kept legible, per Harai building tradition."),
        ],
        "motion": [
            ("MOTION STYLE", "Fast in-betweens, sharp stops. Anticipation poses coiled low; action lines always diagonal."),
            ("WHY", "Animation and pose sheets should express grit kinetically, not just visually."),
        ],
        "motion_note": "When you reach the pose sheets in the workbook, act these notes out physically before drawing them — five seconds of standing the way your character stands teaches more than an hour of reference-hunting.",
        "accent_name": "Hunter Signal",
    },
    # NEW in 2.0 — the archetype on screen (personalized psychology)
    "screen_examples": [
        ("Tanjiro Kamado", "Demon Slayer", "Wound: a family lost in one night. His resilience is gentle, not hard — he endures by refusing to let grief curdle into cruelty. Posture: forward-leaning, weight low, always mid-approach."),
        ("Rock Lee", "Naruto", "Wound: born without the talent his world measures. His survival is repetition made sacred — training as prayer. Posture: coiled symmetry, fists close, a body that has memorised effort."),
        ("Levi Ackerman", "Attack on Titan", "Wound: raised beneath the city that discarded him. Endurance turned to lethal economy — no wasted motion, no wasted trust. Posture: still shoulders, weight centred, eyes doing the moving."),
        ("Violet Evergarden", "Violet Evergarden", "Wound: a childhood spent as a weapon. Survival means learning, word by word, what feelings are. Posture: parade-straight spine slowly learning to soften."),
        ("Thorfinn", "Vinland Saga", "Wound: revenge consumed his youth. True survival begins after the goal dies — rebuilding a self without an enemy. Posture: from crouched aggression to open-handed calm, the arc drawn in stance alone."),
    ],
    "screen_synthesis": "Five Survivors, five different wounds — and notice: none of them is designed around strength. Each is designed around WHAT SURVIVAL COSTS. Their costumes carry the bill: Tanjiro's inherited haori, Lee's bandaged hands, Levi's cravat (the one soft thing), Violet's gloves, Thorfinn's scarred bare arms.",
    "wound_page": {
        "title": "Writing the Wound",
        "intro": "Your record already contains the raw material — read it as a psychologist, then draw it as a designer.",
        "blocks": [
            ("THE WOUND", "Every Survivor design starts from what was survived. Your realm supplies it: The Broken Heart, where calm is always provisional. Decide the ONE event your character measures all others against — you never have to draw the event, only its receipts."),
            ("THE COMPENSATION", "Distrust and Isolation is the shadow — which means the design should show OVER-preparedness: gear for disasters that may never come, exits mapped by habit, a bag never fully unpacked."),
            ("THE SOFT CONTRADICTION", "Give the design one element that argues with the wound — a kept toy, a repaired keepsake, the Relit Hearth token worn openly. The contradiction is where the audience falls in love."),
            ("THE BODY REMEMBERS", "Posture is the wound made visible: weight on the balls of the feet (ready to move), back never fully to a door, hands that check the token when calm. Write three such habits; draw two."),
        ],
    },
}
